name: "Build and Publish"
description: "Build and publish on .NET 7"

runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
              dotnet-version: '8.x.x'
              
        - name: Restore Dependencies
          run: dotnet restore
          shell: bash
          
        - name: Publish
          run: dotnet publish PenumbraModForwarder.UI/ -c Release -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -o ./publish
          shell: bash

        - name: Archive
          run: Compress-Archive -Path ./publish/* -DestinationPath ./publish/PenumbraModForwarder.zip
          shell: pwsh