name: "Build and Test"
description: "Build and test on .NET 9"

runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: '9.x.x'
        
        - name: Restore Dependencies
          run: dotnet restore
          shell: bash

#        - name: Test
#          run: dotnet test
#          shell: bash
          
        - name: Build
          run: dotnet build --configuration Release --no-restore
          shell: bash
          