name: Release on PR Merge

on:
    pull_request:
        types:
            - closed
    
    workflow_dispatch:
        inputs:
            tagName:
                description: "Tag Name"
                required: true
                default: "vX.X.X.X"

permissions:
    contents: write
    packages: write

jobs:
    validate-tag:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: Validate Tag Name
              run: |
                  if [[ ! "${{ github.event.inputs.tagName }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    echo "Invalid tag name format. Please use the format vX.X.X.X"
                    exit 1
                  fi
    
    release:
        if: (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')) || (github.event_name == 'workflow_dispatch')
        runs-on: windows-latest
        needs: validate-tag
        environment: Release
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: 'true'

            - name: Set Tag Name
              id: set_tag
              run: |
                  if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
                    echo "tag_name=${{ github.event.inputs.tagName }}" >> $GITHUB_OUTPUT
                  elif [ "${{ github.event_name }}" == "pull_request" ]; then
                    echo "tag_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
                  else
                    echo "tag_name=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Build and Publish
              uses: ./.github/templates/ReleaseAndPublish

            - name: Generate SHA256 and MD5 hashes for .zip
              run: |
                  sha256sum ./publish/PenumbraModForwarder.zip > ./publish/PenumbraModForwarder.zip.sha256
                  md5sum ./publish/PenumbraModForwarder.zip > ./publish/PenumbraModForwarder.zip.md5

            - name: Read SHA256 and MD5 hashes
              id: read_hashes
              run: |
                  echo "sha256=$(cat ./publish/PenumbraModForwarder.zip.sha256)" >> $GITHUB_ENV
                  echo "md5=$(cat ./publish/PenumbraModForwarder.zip.md5)" >> $GITHUB_ENV

            - name: Get latest commit message from main branch
              id: get_commit_message
              run: |
                  git fetch origin main
                  latest_commit=$(git log origin/main -1 --pretty=%B)
                  echo "commit_message=$latest_commit" >> $GITHUB_ENV

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: ./publish/PenumbraModForwarder.zip
                  retention-days: 3
                  name: "artifact"

            - name: Create Release
              uses: softprops/action-gh-release@v2.0.8
              with:
                  tag_name: ${{ steps.set_tag.outputs.tag_name }}
                  body: |
                      ## Release Notes
                      
                      ${{ env.commit_message }}
                      
                      ## Hashes:
                      - **SHA256 Hash**: `${{ env.sha256 }}`
                      - **MD5 Hash**: `${{ env.md5 }}`
                      
                      ## Download Link
                      [Download the zip](./PenumbraModForwarder.zip)
                  files: |
                      ./publish/PenumbraModForwarder.zip
                      ./publish/PenumbraModForwarder.zip.sha256
                      ./publish/PenumbraModForwarder.zip.md5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
