name: Build and Release on PR Merge

on:
    workflow_run:
        workflows: ["Manual Release"]
        types:
            - completed
        # Ensure this workflow is triggered only after the `update-version` workflow completes
        status: success

jobs:
    build-release-upload:
        if: github.event.workflow_run.workflow == 'Manual Release' && github.event.workflow_run.conclusion == 'success'
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Build and Publish
              uses: ./.github/templates/ReleaseAndPublish

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: ./publish/PenumbraModForwarder.zip
                  retention-days: 3
                  name: "artifact"

            - name: Create Release
              uses: softprops/action-gh-release@v2.0.8
              with:
                  tag_name: ${{ github.event.pull_request.head.ref }}
                  files: ./publish/PenumbraModForwarder.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
