name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag Name"
        required: true
        default: "vX.X.X.X"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Tag Name
        run: |
          if [[ ! "${{ github.event.inputs.tagName }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag name format. Please use the format vX.X.X.X"
            exit 1
          fi

  update-version:
    runs-on: ubuntu-latest
    needs: validate-tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update XML and Update URL
        run: |
          version="${{ github.event.inputs.tagName }}"
          version_stripped="${version#v}"  # Strip the leading 'v'
          xml_file="./update.xml"
          xml=$(cat "$xml_file")
          xml=$(echo "$xml" | sed "s|<version>.*</version>|<version>${version_stripped}</version>|")
          xml=$(echo "$xml" | sed "s|<url>.*</url>|<url>https://github.com/Sebane1/PenumbraModForwarder/releases/download/${version}/PenumbraModForwarder.zip</url>|")
          echo "$xml" > "$xml_file"
        shell: bash

      - name: Update .csproj Version
        run: |
          version="${{ github.event.inputs.tagName }}"
          version="${version#v}"  # Strip the leading 'v'
          csproj_file="./PenumbraModForwarder/PenumbraModForwarder.csproj"
          sed -i "s|<Version>.*</Version>|<Version>${version}</Version>|" "$csproj_file"
        shell: bash

      - name: Commit Changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "[AUTO-COMMIT] Update Version Number"
          target_branch: ${{ github.event.inputs.tagName }}

      - name: Create a PR with the changes
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Version Number"
          source_branch: ${{ github.event.inputs.tagName }}
          target_branch: "master"
          get_diff: 'true'
          label: 'release'
